### ISSUE TITLE
Streamline the deployment process

### ISSUE THREAD

**Issue by Monkeyanator** [kubernetes-sigs/mutating-trace-admission-controller#3]
At the moment, before users can deploy this controller in their cluster, they have to run scripts from our `hack` folder to perform certificate generation and configuration for the webhook. 

As much as possible, we should move towards a deployment scheme wherein users can simply apply config to their cluster and have this controller running. In addition, it should be possible, either through [`kustomize`](https://github.com/kubernetes-sigs/kustomize) or other means, to customize the webhook (common use case might be to set sampling rate higher in environments farther from prod).

**Comment by dashpole** [comment]
It looks like kustomize supports secret generation: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/generatorOptions.md#generator-options.  I came across this watching a kubecon talk: https://www.youtube.com/watch?v=ahMIBxufNR0&index=73&list=PLj6h78yzYM2PZf9eA7bhWnIh_mK1vyOfU
