### ISSUE TITLE
k8s.gcr.io/trace-context-injector:latest does not exist

### ISSUE THREAD

**Issue by mattysweeps** [kubernetes-sigs/mutating-trace-admission-controller#8]
I followed the README and ran `make cluster-up` but my pods fails to pull the container image `k8s.gcr.io/trace-context-injector:latest`

Should this container image exist? Is it expected that In always build it myself?

**Comment by dashpole** [comment]
The controller tracing KEP no longer proposes using an admission controller.  I don't remember if we ever pushed the image to k8s.gcr.io.  If you are still interested in trying to use the admission controller, you can build and push it yourself, and update https://github.com/kubernetes-sigs/mutating-trace-admission-controller/blob/master/deploy/base/deployment.yaml#L14 locally to point at your image.

**Comment by mattysweeps** [comment]
Thanks @dashpole 

Should the Readme be updated such that it states that `The controller tracing KEP no longer proposes using an admission controller`?

**Comment by dashpole** [comment]
Sounds good.  I opened a pull request.
